# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

basicsolution3cptm <- function(tm, kR, k10, k12, k21, k13, k31, v1, v2, v3, ke0, c0) {
    .Call(`_tci_basicsolution3cptm`, tm, kR, k10, k12, k21, k13, k31, v1, v2, v3, ke0, c0)
}

pksol3cptm <- function(tms, pars, begin, end, infs, init) {
    .Call(`_tci_pksol3cptm`, tms, pars, begin, end, infs, init)
}

